### ISSUE TITLE
script folder is missing

### ISSUE THREAD

**Issue by hangzhiyiwei** [GATECH-EIC/Hint-Aug#1]
Hi, thanks for your nice work.

I saw that your scripts are stored in the script folder. However, maybe you forgot to submit it. Any reply will be appreciated. Thanks very much.

Best,
hangzhiyiwei

**Comment by Yuzz1020** [comment]
Hi hangzhiyiwei, 

Thank you for the issue and sorry for the confusion! We just updated the codebase with the missing script folder. 

I'm closing this comment. If you have any further questions, please feel free to reopen it. 

Regards,
Zhongzhi
